In [1]:
import pandas as pd
import json
import os

# Excel 파일 경로
excel_file = r'C:\Users\ch.kang\Desktop\4월투어\ga_20240419.xlsx'

# 만든 고유 아이디 매핑 파일 경로
mapping_file = r'C:\Users\ch.kang\OneDrive - 클리 주식회사\문서 - 클리주식회사\000_Routine_마이세컨플레이스\02. IT Platform&Data\01_콘텐츠성과측정\02_ConvertedData\id_mapping.json'

# 데이터프레임 로드
df = pd.read_excel(excel_file, dtype=str)

# 고유 아이디 매핑 파일 로드
with open(mapping_file, 'r') as f:
    id_mapping = json.load(f)

# UniqueIDGenerator 클래스
class UniqueIDGenerator:
    def __init__(self, id_mapping):
        self.id_mapping = id_mapping

    def get_unique_id(self, username):
        return self.id_mapping.get(username, None)

# UniqueIDGenerator 인스턴스 생성
generator = UniqueIDGenerator(id_mapping)

# 고유 아이디 생성 및 데이터프레임에 추가
df['고유아이디'] = df['아이디'].apply(generator.get_unique_id)

# 결과 확인
print(df)

                        아이디                                 익명아이디  \
0     1013558053.1713492811  d66911f1-ae80-494e-a6f4-e2832b347fb5
1     1013558053.1713492811  d66911f1-ae80-494e-a6f4-e2832b347fb5
2     1013558053.1713492811  d66911f1-ae80-494e-a6f4-e2832b347fb5
3     1013558053.1713492811  d66911f1-ae80-494e-a6f4-e2832b347fb5
4     1026303159.1713536777  79c7bcc2-9e88-4252-9612-95f10eada563
...                     ...                                   ...
1457   976792900.1713494186  12ae7455-835c-4428-b393-47df4ea9254e
1458   976792900.1713494186  12ae7455-835c-4428-b393-47df4ea9254e
1459    98499439.1713525360  dfa32e4d-f3f9-404f-8583-9ee5e0f35100
1460    98499439.1713525360  dfa32e4d-f3f9-404f-8583-9ee5e0f35100
1461   988079601.1710122751  8ba03d5f-39c9-4836-99f0-d824e15f2cd1

                            시간             이벤트명                  페이지제목  \
0     2024. 4. 19. 오전 11:13:32      first_visit         시골땅 시골집 전문가 상담
1     2024. 4. 19. 오전 11:13:32        page_view         시골땅 시골집 전문가 상담
2     2024. 4. 19. 오전 11:13:38           scroll         시골땅 시골집 전문가 상담
3     2024. 4. 19. 오전 11:14:29  user_engagement         시골땅 시골집 전문가 상담
4     2024. 4. 19. 오후 11:26:17      first_visit       마이세컨플레이스 뉴스레터 구독
...                        ...              ...                    ...
1457  2024. 4. 19. 오전 11:36:26        page_view       마이세컨플레이스 뉴스레터 구독
1458  2024. 4. 19. 오전 11:36:31           scroll       마이세컨플레이스 뉴스레터 구독
1459   2024. 4. 19. 오후 8:16:04      first_visit  모두를 위한 세컨하우스 마이세컨플레이스
1460   2024. 4. 19. 오후 8:16:04        page_view  모두를 위한 세컨하우스 마이세컨플레이스
1461   2024. 4. 19. 오후 8:34:25        page_view       마이세컨플레이스 뉴스레터 구독

                                                  정규화링크  \
0     https://mysecondplace.co.kr/secondhouse_servic...
1     https://mysecondplace.co.kr/secondhouse_servic...
2     https://mysecondplace.co.kr/secondhouse_servic...
3     https://mysecondplace.co.kr/secondhouse_servic...
4     https://mysecondplace.co.kr/newsletter_embed/?...
...                                                 ...
1457  https://mysecondplace.co.kr/newsletter_embed/?...
1458  https://mysecondplace.co.kr/newsletter_embed/?...
1459  https://mysecondplace.co.kr/post_a_03/?utm_id=...
1460  https://mysecondplace.co.kr/post_a_03/?utm_id=...
1461  https://mysecondplace.co.kr/newsletter_embed/?...

                                                   원래링크         소스  \
0     https://mysecondplace.co.kr/secondhouse_servic...    youtube
1     https://mysecondplace.co.kr/secondhouse_servic...    youtube
2     https://mysecondplace.co.kr/secondhouse_servic...    youtube
3     https://mysecondplace.co.kr/secondhouse_servic...    youtube
4     https://mysecondplace.co.kr/newsletter_embed?u...  instagram
...                                                 ...        ...
1457  https://mysecondplace.co.kr/newsletter_embed?u...  instagram
1458  https://mysecondplace.co.kr/newsletter_embed?u...  instagram
1459  https://mysecondplace.co.kr/post_a_03?utm_sour...  instagram
1460  https://mysecondplace.co.kr/post_a_03?utm_sour...  instagram
1461  https://mysecondplace.co.kr/newsletter_embed?u...  instagram

              매체      캠페인                           컨텐츠                 검색어  \
0          video    video  https://youtu.be/uBeB4dlWIBA                 NaN
1          video    video  https://youtu.be/uBeB4dlWIBA                 NaN
2          video    video  https://youtu.be/uBeB4dlWIBA                 NaN
3          video    video  https://youtu.be/uBeB4dlWIBA                 NaN
4     newsletter   뉴스레터구독                      04_보내드려요  120207724210750057
...          ...      ...                           ...                 ...
1457  newsletter   뉴스레터구독                      04_보내드려요  120207724210750057
1458  newsletter   뉴스레터구독                      04_보내드려요  120207724210750057
1459  postagroup  포스트에이그룹                     04_또망가질테니  120208619941940057
1460  postagroup  포스트에이그룹                     04_또망가질테니  120208619941940057
1461  newsletter   뉴스레터구독                      04_보내드려요  120207724210750057

     engagement_time 체류시간 전환여부     고유아이디
0                NaN    0  NaN  g-000001
1                NaN    5  NaN  g-000001
2              0.033   51  NaN  g-000001
3             23.366  NaN  NaN  g-000001
4                NaN    0  NaN  g-000002
...              ...  ...  ...       ...
1457             NaN    4  NaN  g-000198
1458             NaN  NaN  NaN  g-000198
1459             NaN    0  NaN  g-000199
1460             NaN  NaN  NaN  g-000199
1461             NaN  NaN  NaN  g-014871

[1462 rows x 16 columns]

In [2]:
# 'conversion' 열 생성
df['conversion'] = ''
df['원래링크'] = df['원래링크'].fillna('')
df.columns

Index(['아이디', '익명아이디', '시간', '이벤트명', '페이지제목', '정규화링크', '원래링크', '소스', '매체',
       '캠페인', '컨텐츠', '검색어', 'engagement_time', '체류시간', '전환여부', '고유아이디',
       'conversion'],
      dtype='object')

In [3]:


# '원래링크' 열에서 특정 문자열이 포함된 경우, 'conversion' 열에 해당 값 추가
df.loc[df['원래링크'].str.contains('bmode=view&idx=17967442').fillna(False), 'conversion'] = 'blog_1'
df.loc[df['원래링크'].str.contains('/tour_application_blog').fillna(False), 'conversion'] = 'blog_2'
df.loc[df['원래링크'].str.contains('/tour_completed_blog').fillna(False), 'conversion'] = 'blog_3'
df.loc[df['원래링크'].str.contains('/gongju_msp2').fillna(False), 'conversion'] = 'market_1'
df.loc[df['원래링크'].str.contains('/tour_application_gongju').fillna(False), 'conversion'] = 'market_2'
df.loc[df['원래링크'].str.contains('/tour_completed_gongju').fillna(False), 'conversion'] = 'market_3'
df.loc[df['원래링크'].str.contains('/pb_secondhouse_ads').fillna(False), 'conversion'] = 'pb_1'
df.loc[df['원래링크'].str.contains('/tour_application_pb').fillna(False), 'conversion'] = 'pb_2'
df.loc[df['원래링크'].str.contains('/tour_completed_pb').fillna(False), 'conversion'] = 'pb_3'
df.loc[df['원래링크'].str.contains('/m_npz').fillna(False), 'conversion'] = 'main_1'
df.loc[df['원래링크'].str.contains('/tour_application_m').fillna(False), 'conversion'] = 'main_2'
df.loc[df['원래링크'].str.contains('/tour_completed_m').fillna(False), 'conversion'] = 'main_3'
df.loc[df['원래링크'].str.contains('/tour_notice_q_q').fillna(False), 'conversion'] = 'qq_1'
df.loc[df['원래링크'].str.contains('/tour_application_q_q').fillna(False), 'conversion'] = 'qq_2'
df.loc[df['원래링크'].str.contains('/tour_completed_q_q').fillna(False), 'conversion'] = 'qq_3'
df.loc[df['원래링크'].str.contains('/tour_notice_q_l').fillna(False), 'conversion'] = 'ql_1'
df.loc[df['원래링크'].str.contains('/tour_application_q_l').fillna(False), 'conversion'] = 'ql_2'
df.loc[df['원래링크'].str.contains('/tour_completed_q_l').fillna(False), 'conversion'] = 'ql_3'
df.loc[df['원래링크'].str.contains('/tour_notice_l_q').fillna(False), 'conversion'] = 'lq_1'
df.loc[df['원래링크'].str.contains('/tour_application_l_q').fillna(False), 'conversion'] = 'lq_2'
df.loc[df['원래링크'].str.contains('/tour_completed_l_q').fillna(False), 'conversion'] = 'lq_3'
df.loc[df['원래링크'].str.contains('/tour_notice_l_l').fillna(False), 'conversion'] = 'll_1'
df.loc[df['원래링크'].str.contains('/tour_application_l_l').fillna(False), 'conversion'] = 'll_2'
df.loc[df['원래링크'].str.contains('/tour_completed_l_l').fillna(False), 'conversion'] = 'll_3'
df.loc[df['원래링크'].str.contains('/tour_notice_q_q_g').fillna(False), 'conversion'] = 'qqg_1'
df.loc[df['원래링크'].str.contains('/tour_application_q_q_g').fillna(False), 'conversion'] = 'qqg_2'
df.loc[df['원래링크'].str.contains('/tour_completed_q_q_g').fillna(False), 'conversion'] = 'qqg_3'
df.loc[df['원래링크'].str.contains('/tour_notice_l_q_g').fillna(False), 'conversion'] = 'lqg_1'
df.loc[df['원래링크'].str.contains('/tour_application_l_q_g').fillna(False), 'conversion'] = 'lqg_2'
df.loc[df['원래링크'].str.contains('/tour_completed_l_q_g').fillna(False), 'conversion'] = 'lqg_3'

In [4]:
df_pageview = df[df['이벤트명'] == 'page_view']
df_pageview.head(5)

,아이디,익명아이디,시간,이벤트명,페이지제목,정규화링크,원래링크,소스,매체,캠페인,컨텐츠,검색어,engagement_time,체류시간,전환여부,고유아이디,conversion
1,1013558053.1713492811,d66911f1-ae80-494e-a6f4-e2832b347fb5,2024. 4. 19. 오전 11:13:32,page_view,시골땅 시골집 전문가 상담,https://mysecondplace.co.kr/secondhouse_servic...,https://mysecondplace.co.kr/secondhouse_servic...,youtube,video,video,https://youtu.be/uBeB4dlWIBA,NaN,NaN,5,NaN,g-000001,
5,1026303159.1713536777,79c7bcc2-9e88-4252-9612-95f10eada563,2024. 4. 19. 오후 11:26:17,page_view,마이세컨플레이스 뉴스레터 구독,https://mysecondplace.co.kr/newsletter_embed/?...,https://mysecondplace.co.kr/newsletter_embed?u...,instagram,newsletter,뉴스레터구독,04_보내드려요,120207724210750057,NaN,NaN,NaN,g-000002,
6,1026331129.1707742178,81de781e-2029-4283-98c4-6471a5f13a00,2024. 4. 19. 오전 6:13:22,page_view,모두를 위한 세컨하우스 마이세컨플레이스,https://mysecondplace.co.kr/login,https://mysecondplace.co.kr/?mode=login&back_u...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,g-002807,
7,1026331129.1707742178,81de781e-2029-4283-98c4-6471a5f13a00,2024. 4. 19. 오전 6:13:23,page_view,모두를 위한 세컨하우스 마이세컨플레이스,https://mysecondplace.co.kr/login,https://mysecondplace.co.kr/login?back_url=L2F...,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,g-002807,
11,1030956150.1713527763,f0737ec1-8292-4c68-9486-50670da7c29c,2024. 4. 19. 오후 8:56:03,page_view,마이세컨플레이스 뉴스레터 구독,https://mysecondplace.co.kr/newsletter_embed/?...,https://mysecondplace.co.kr/newsletter_embed?u...,instagram,newsletter,뉴스레터구독,04_보내드려요,120207724210750057,NaN,0,NaN,g-000003,

In [5]:
# conversion에 따라 고유 아이디를 표로 정리합니다.
conversion_ids = df_pageview.groupby('conversion')['고유아이디'].apply(list).reset_index()
only_conversion_ids = conversion_ids.drop(0)
expanded_ids = only_conversion_ids.explode('고유아이디')

In [6]:
expanded_ids
# conversion을 기준으로 그룹화하여 '고유아이디'를 리스트로 묶기
grouped_ids = expanded_ids.groupby('conversion')['고유아이디'].apply(list).reset_index()
grouped_ids['고유아이디'] = grouped_ids['고유아이디'].astype(str)
grouped_ids['고유아이디'] = grouped_ids['고유아이디'].str.replace('[', '').str.replace(']', '')

In [7]:
df_expanded = grouped_ids['고유아이디'].str.split(',', expand=True)
df_result = pd.concat([grouped_ids, df_expanded], axis=1)
df_result = df_result.drop(columns=['고유아이디'])

In [8]:
conversion_df=df_result.T
# 1번째 행을 새로운 열 헤더로 설정
new_header = conversion_df.iloc[0]
conversion_df = conversion_df[1:]
conversion_df = conversion_df.set_axis(new_header, axis=1)
conversion_df.loc['Count'] = conversion_df.count()
conversion_df = conversion_df.reindex(index=['Count'] + conversion_df.index[:-1].tolist())

In [9]:
conversion_df

conversion,blog_1,lq_1,lqg_1,main_2,market_1,market_2,pb_1,qq_1,qqg_1
Count,3,3,1,1,19,1,19,1,5
0,'g-000058','g-000048','g-000103','g-000175','g-000005','g-009642','g-000018','g-000811','g-000099'
1,'g-009642','g-000135',None,None,'g-000123',None,'g-000018',None,'g-000099'
2,'g-009642','g-000135',None,None,'g-000868',None,'g-000018',None,'g-000099'
3,None,None,None,None,'g-000036',None,'g-000018',None,'g-000099'
4,None,None,None,None,'g-000058',None,'g-000030',None,'g-001109'
5,None,None,None,None,'g-000099',None,'g-000868',None,None
6,None,None,None,None,'g-000101',None,'g-000046',None,None
7,None,None,None,None,'g-005892',None,'g-019145',None,None
8,None,None,None,None,'g-005892',None,'g-000077',None,None
9,None,None,None,None,'g-000135',None,'g-000077',None,None
10,None,None,None,None,'g-009642',None,'g-000077',None,None
11,None,None,None,None,'g-009642',None,'g-000077',None,None
12,None,None,None,None,'g-009642',None,'g-000077',None,None
13,None,None,None,None,'g-009642',None,'g-000099',None,None
14,None,None,None,None,'g-009642',None,'g-000101',None,None
15,None,None,None,None,'g-004539',None,'g-000111',None,None
16,None,None,None,None,'g-000167',None,'g-009642',None,None
17,None,None,None,None,'g-000811',None,'g-000171',None,None
18,None,None,None,None,'g-000192',None,'g-000189',None,None

In [10]:
output_path = os.path.join(os.path.dirname(excel_file), 'conversion_' + os.path.basename(excel_file))

with pd.ExcelWriter(output_path) as writer:
    # df를 첫 번째 시트로 저장
    df.to_excel(writer, sheet_name='rawdata', index=False)
    
    # conversion_ids를 두 번째 시트로 저장
    conversion_df.to_excel(writer, sheet_name='conversion_ids', index=False)